# Generated by Django 6.1 on 2026-08-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyelderrelationship',
            name='can_manage_appointments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familyelderrelationship',
            name='can_manage_emergency_contacts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familyelderrelationship',
            name='can_manage_medicines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familyelderrelationship',
            name='can_receive_sos',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='familyelderrelationship',
            name='elder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relationships', to='accounts.elderprofile'),
        ),
        migrations.AlterField(
            model_name='familyelderrelationship',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elder_relationships', to='accounts.familyprofile'),
        ),
        migrations.AlterField(
            model_name='familyelderrelationship',
            name='relationship_type',
            field=models.CharField(blank=True, help_text='Example: Son, Daughter, Spouse, Caregiver', max_length=50),
        ),
    ]
