# Generated by Django 6.1 on 2026-08-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_familyelderrelationship_can_manage_appointments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderprofile',
            name='careconnect_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='familyelderrelationship',
            name='relationship_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('relationship_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_received', to='accounts.elderprofile')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_sent', to='accounts.familyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
