# Generated by Django 6.1 on 2026-08-15 13:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_elderprofile_careconnect_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='elderprofile',
            name='careconnect_id',
            field=models.CharField(db_index=True, default=accounts.models.generate_careconnect_id, editable=False, max_length=9, unique=True),
        ),
    ]
