# Generated by Django 6.1 on 2026-08-17 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('clinic_name', models.CharField(max_length=200)),
                ('appointment_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='SCHEDULED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to='accounts.familyprofile')),
                ('elder', models.ForeignKey(db_column='elder_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.elderprofile')),
            ],
            options={
                'db_table': 'appointments_appointment',
                'ordering': ['appointment_at'],
            },
        ),
    ]
