import { FaBell, FaCalendarDays, FaCapsules, FaCircleCheck, FaClock, FaHeartPulse, FaLocationDot, FaRobot, FaTriangleExclamation, FaUser, FaWheelchair } from "react-icons/fa6";
import { Link, useNavigate } from "react-router-dom";

export function ElderHeader({ name, onAccessibility }) {
  return <header className="elder-header"><Link to="/elder/dashboard" className="elder-brand"><FaHeartPulse /> Care<span>Connect</span></Link><p className="elder-header-greeting">Good day{name ? `, ${name}` : ""}</p><div className="elder-header-actions"><button type="button" aria-label="Accessibility settings" onClick={onAccessibility}><FaWheelchair /><span>Text size</span></button><button type="button" aria-label="Notifications"><FaBell /><span className="sr-only">Notifications</span></button></div></header>;
}
export function SOSCard({ onOpen }) { return <section className="sos-card" aria-labelledby="sos-title"><div><p className="section-eyebrow"><FaTriangleExclamation /> Emergency help</p><h2 id="sos-title">Need immediate assistance?</h2><p>Press SOS if you need emergency help now.</p></div><button className="sos-button" type="button" onClick={onOpen} aria-label="Open emergency SOS confirmation"><FaHeartPulse /><strong>SOS</strong><small>Emergency Help</small></button></section>; }
function MedicineRow({ medicine, onTake }) { const status = medicine.status || "upcoming"; return <li className="medicine-row"><div className="medicine-time"><FaClock />{formatTime(medicine.scheduled_time)}</div><div className="medicine-icon"><FaCapsules /></div><div className="medicine-details"><strong>{medicine.name}</strong><span>{medicine.dosage}</span><small>{medicine.instructions}</small></div><div className="medicine-action"><span className={`status status-${status}`}>{status === "taken" ? "Taken" : status === "due" ? "Due now" : status}</span>{status !== "taken" && <button type="button" onClick={() => onTake(medicine.id)}>Mark as taken</button>}</div></li>; }
export function MedicineCard({ medicines, onTake }) { return <section className="care-card medicines-card" aria-labelledby="medicines-title"><div className="card-heading"><div><p className="section-eyebrow"><FaCapsules /> Today’s care</p><h2 id="medicines-title">Today’s Medicines</h2></div><Link to="/elder/medicines">View all</Link></div>{medicines.length ? <ul className="medicine-list">{medicines.map((medicine) => <MedicineRow key={medicine.id} medicine={medicine} onTake={onTake} />)}</ul> : <Empty icon={<FaCapsules />} text="No medicines have been scheduled for today." />}</section>; }
export function AppointmentCard({ appointments }) { const appointment = appointments[0]; return <section className="care-card appointment-card" aria-labelledby="appointment-title"><div className="card-heading"><div><p className="section-eyebrow"><FaCalendarDays /> Coming up</p><h2 id="appointment-title">Upcoming Appointment</h2></div><Link to="/elder/appointments">View all</Link></div>{appointment ? <div className="appointment-content"><div className="doctor-avatar"><FaUser /></div><div><strong>{appointment.doctor_name}</strong><p>{appointment.specialization}</p></div><p className="appointment-when"><b>{appointment.date_label}</b><span><FaClock /> {appointment.time}</span></p><p className="appointment-location"><FaLocationDot /> {appointment.location}</p><Link className="soft-button" to="/elder/appointments">View appointment</Link></div> : <Empty icon={<FaCalendarDays />} text="You don’t have any upcoming appointments." />}</section>; }
export function CompanionCard() { return <section className="companion-card"><div className="companion-icon"><FaRobot /></div><div><p className="section-eyebrow">CareConnect AI Companion</p><h2>Want to talk? I’m here to listen.</h2><p>How are you feeling today?</p></div><Link to="/elder/ai-companion">Start conversation</Link></section>; }
export function DailySummary({ medicines, appointment }) { const remaining = medicines.filter((medicine) => medicine.status !== "taken").length; return <section className="care-card summary-card"><p className="section-eyebrow">A simple overview</p><h2>Your Day</h2><ul><li><FaCircleCheck />{medicines.some((medicine) => medicine.status === "taken") ? "Medicine taken today" : "Your medicines are ready"}</li><li><FaCalendarDays />{appointment ? `Appointment ${appointment.date_label?.toLowerCase() || "coming up"}` : "No appointment coming up"}</li><li className={remaining ? "pending" : ""}><FaClock />{remaining ? `${remaining} medicine${remaining > 1 ? "s" : ""} still pending` : "All medicines complete"}</li></ul></section>; }
export function QuickActions({ onSOS }) { const navigate = useNavigate(); const actions = [[FaCapsules, "Medicines", "/elder/medicines"], [FaCalendarDays, "Appointments", "/elder/appointments"], [FaRobot, "AI Companion", "/elder/ai-companion"], [FaUser, "My Profile", "/elder/profile"]]; return <section className="quick-actions"><h2>Quick Actions</h2><div>{actions.map(([Icon, label, path]) => <button key={label} type="button" onClick={() => navigate(path)}><Icon /><span>{label}</span></button>)}<button className="quick-sos" type="button" onClick={onSOS}><FaTriangleExclamation /><span>Emergency SOS</span></button></div></section>; }
export function Empty({ icon, text }) { return <div className="empty-state">{icon}<p>{text}</p></div>; }
function formatTime(time) { if (!time) return "Time not set"; if (/am|pm/i.test(time)) return time; const [hours, minutes] = time.split(":").map(Number); return new Date(2000, 0, 1, hours, minutes).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); }
