# Generated by Django 6.1 on 2026-08-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('can_receive_sos', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(db_column='elder_id', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='accounts.elderprofile')),
            ],
            options={
                'db_table': 'emergency_contacts_emergencycontact',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
