# Generated by Django 6.1 on 2026-08-16 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('instructions', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.elderprofile')),
            ],
            options={
                'ordering': ['scheduled_time', 'name'],
            },
        ),
    ]
