# Generated by Django 6.1 on 2026-08-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers'),
        ('medicines', '0002_alter_medicine_options_remove_medicine_instructions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='elder',
            field=models.ForeignKey(db_column='elder_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='accounts.elderprofile'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='food_timing',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='medicines_medicine',
        ),
    ]
