# Generated by Django 6.1 on 2026-10-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_medicine_options_alter_medicine_elder_and_more'),
        ('medicines', '0003_medicine_add_missing_fields'),
    ]

    operations = [
    ]
