# Generated by Django 6.1 on 2026-10-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_merge_20261003_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='food_timing',
            field=models.CharField(blank=True, default='ANY', max_length=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(default='Once daily', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
